window.createClassDiary=function({read,put}){
 const root=document.createElement('section');root.id='diaryScreen';root.hidden=true;root.setAttribute('role','tabpanel');root.setAttribute('aria-labelledby','diaryTab');root.innerHTML=`<div class="diary-heading"><h1>알림장</h1><label>작성 날짜 <input id="diaryDate" type="date"></label></div><div class="diary-actions"><button id="diaryConnect">하이클래스 연결 / 다시 로그인</button><button id="diaryLink">현재 하이클래스 학급 연결</button><button id="diaryImport">대시보드 내용 불러오기</button></div><label>제목<input id="diaryTitle"></label><label>본문<textarea id="diaryBody" placeholder="학생과 가정에 전할 내용을 적어 주세요."></textarea></label><div class="diary-actions"><strong>하이클래스 수신대상</strong><label><input id="diaryParents" type="checkbox" checked> 학부모 수신</label><label><input id="diaryStudents" type="checkbox" checked> 학생 수신</label></div><div class="diary-actions"><span id="diaryStatus" role="status"></span><button id="diaryPublish" class="primary">하이클래스 등록</button></div><dialog id="diaryImportDialog"><h2>필요한 내용만 선택하세요</h2><div id="diaryCandidates"></div><button id="diaryImportApply">선택 내용 추가</button><button id="diaryImportCancel">취소</button></dialog>`;document.body.append(root);
 const $=id=>root.querySelector('#'+id);let drafts=read('diaryDrafts',{}),date=Core.dateKey(),key,busy=false,connecting=false;
 const classId=()=>`${academicYear()}:${settings.grade||''}:${settings.classroom||''}`;
 const title=d=>{const day=new Date(d+'T12:00:00');return `${day.getMonth()+1}월 ${day.getDate()}일 ${['일','월','화','수','목','금','토'][day.getDay()]}요일 알림장`;};
 function load(){key=classId()+':'+date;const draft=drafts[key]||{title:title(date),body:''};$('diaryDate').value=date;$('diaryTitle').value=draft.title;$('diaryBody').value=draft.body;$('diaryParents').checked=draft.parents!==false;$('diaryStudents').checked=draft.students!==false;$('diaryStatus').textContent=draft.postedHash?'이 날짜에 등록한 기록이 있습니다.':'작성 내용은 자동 저장됩니다.';}
 function save(){drafts[key]={...drafts[key],title:$('diaryTitle').value,body:$('diaryBody').value,parents:$('diaryParents').checked,students:$('diaryStudents').checked,updatedAt:Date.now()};const ok=put('diaryDrafts',drafts);$('diaryStatus').textContent=ok?'저장됨':'저장 공간을 확인해 주세요.';return ok;}
 const noTarget=()=>!$('diaryParents').checked&&!$('diaryStudents').checked,NO_TARGET='학부모 또는 학생 중 한 곳 이상을 수신대상으로 선택해 주세요.';
 $('diaryParents').onchange=$('diaryStudents').onchange=()=>{save();if(noTarget())$('diaryStatus').textContent=NO_TARGET;};$('diaryTitle').oninput=save;$('diaryBody').oninput=save;$('diaryDate').onchange=()=>{if(!$('diaryDate').value)return;save();date=$('diaryDate').value;load();};
 async function run(action){try{const result=await action();$('diaryStatus').textContent=result.message;return result;}catch{$('diaryStatus').textContent='하이클래스에 연결하지 못했습니다. 작성 내용은 유지됩니다.';}}
 async function connect(action){
  if(connecting||busy)return;connecting=true;
  $('diaryConnect').disabled=true;$('diaryLink').disabled=true;$('diaryPublish').disabled=true;
  $('diaryStatus').textContent='하이클래스 연결 중…';
  try{await run(action);}finally{connecting=false;$('diaryConnect').disabled=false;$('diaryLink').disabled=false;$('diaryPublish').disabled=busy;}
 }
 $('diaryConnect').onclick=()=>connect(()=>window.desktop.diaryConnect());
 $('diaryLink').onclick=()=>connect(()=>window.desktop.diaryLink({classKey:classId(),label:`${settings.grade}학년 ${settings.classroom}반`}));
 $('diaryPublish').onclick=async()=>{if(busy||connecting||!save())return;if(!$('diaryTitle').value.trim()||!$('diaryBody').value.trim()){$('diaryStatus').textContent='제목과 본문을 입력해 주세요.';return;}if(noTarget()){$('diaryStatus').textContent=NO_TARGET;return;}busy=true;$('diaryPublish').disabled=true;$('diaryPublish').textContent='하이클래스 등록 중...';const postingKey=key;const payload={classKey:classId(),date,title:$('diaryTitle').value,body:$('diaryBody').value,parents:$('diaryParents').checked,students:$('diaryStudents').checked};$('diaryStatus').textContent='등록 상태 확인 중…';try{const result=await run(()=>window.desktop.diaryPublish(payload));if(result?.status==='success'){drafts[postingKey]={...drafts[postingKey],postedHash:result.hash};put('diaryDrafts',drafts);}}finally{busy=false;$('diaryPublish').disabled=false;$('diaryPublish').textContent='하이클래스 등록';}};
 $('diaryImport').onclick=()=>{const items=[];const notices=document.getElementById('notices')?.innerText.trim();if(notices)items.push({label:'안내사항 / 준비물 / 전달사항',text:notices});for(const el of document.querySelectorAll('#ddayBadge span'))items.push({label:'D-Day 일정',text:el.textContent});$('diaryCandidates').replaceChildren(...items.map(item=>{const label=document.createElement('label'),check=document.createElement('input'),span=document.createElement('span');check.type='checkbox';check.dataset.text=item.text;span.textContent=item.label+'\n'+item.text;label.append(check,span);return label;}));if(!items.length)$('diaryCandidates').textContent='불러올 안내사항이나 D-Day가 없습니다.';$('diaryImportDialog').showModal();};
 $('diaryImportCancel').onclick=()=>$('diaryImportDialog').close();$('diaryImportApply').onclick=()=>{const texts=[...$('diaryCandidates').querySelectorAll('input:checked')].map(x=>x.dataset.text);if(texts.length){$('diaryBody').value=[$('diaryBody').value,...texts].filter(Boolean).join('\n\n');save();}$('diaryImportDialog').close();};
 return {activate(active){if(!root.hidden&&key)save();root.hidden=!active;if(active)load();}};
};
