(() => {
 if(!window.desktop?.updateState)return;
 const box=document.createElement('aside');box.id='updateNotice';box.hidden=true;box.setAttribute('role','status');
 const text=document.createElement('span'),button=document.createElement('button'),close=document.createElement('button');button.textContent='업데이트';close.textContent='나중에';box.append(text,button,close);document.body.append(box);
 const dialog=document.createElement('dialog');dialog.id='updateDialog';dialog.innerHTML='<h2>앱 업데이트</h2><p id="installedVersion"></p><p id="updateStatus" role="status"></p><div class="actions"><button type="button" id="checkUpdate">업데이트 확인</button><button type="button" id="installUpdate" hidden>업데이트</button><button type="button" id="closeUpdate">닫기</button></div>';document.body.append(dialog);
 const check=dialog.querySelector('#checkUpdate'),install=dialog.querySelector('#installUpdate');
 let dismissed=false,state={phase:'idle'};
 const message=s=>s.phase==='available'?`새 버전 ${s.version}이 있습니다`:s.phase==='checking'?'새 버전을 확인하고 있습니다…':s.phase==='current'?'최신 버전을 사용하고 있습니다.':s.phase==='downloading'?`새 버전 다운로드 중 · ${s.percent||0}%`:s.phase==='preparing'?'데이터와 이전 버전을 보관하고 있습니다':s.phase==='installing'?'업데이트 후 다시 시작합니다':s.phase==='unconfigured'?'업데이트 배포 주소가 설정되지 않았습니다.':s.message||'업데이트 확인 버튼을 눌러 주세요.';
 function render(s){state=s;for(const launch of document.querySelectorAll('.open-update')){const available=s.phase==='available'||(s.phase==='error'&&s.version);launch.classList.toggle('update-available',Boolean(available));launch.textContent=available?'새 버전 업데이트':'업데이트';launch.setAttribute('aria-label',available?'새 버전이 있습니다. 업데이트':'업데이트');}const working=['checking','downloading','preparing','installing'].includes(s.phase),available=s.phase==='available'||(s.phase==='error'&&s.version);box.hidden=dismissed||!['available','downloading','preparing','installing','error'].includes(s.phase);text.textContent=message(s);button.hidden=!available;close.hidden=!['available','error'].includes(s.phase);dialog.querySelector('#installedVersion').textContent=`현재 버전 ${s.currentVersion||'—'}`;dialog.querySelector('#updateStatus').textContent=message(s);check.disabled=working;install.hidden=!available;install.disabled=working;}
 async function checkNow(){dismissed=false;try{render(await window.desktop.checkUpdate());}catch{render({...state,phase:'check-error',message:'업데이트를 확인하지 못했습니다. 다시 시도해 주세요.'});}}
 function open(){if(!dialog.open)dialog.showModal();if(!['available','downloading','preparing','installing','checking'].includes(state.phase))checkNow();}
 for(const parent of [document.querySelector('#settingsForm .actions')]){if(!parent)continue;const launch=document.createElement('button');launch.type='button';launch.className='open-update';launch.textContent='업데이트';launch.onclick=open;parent.append(launch);}
 check.onclick=checkNow;install.onclick=button.onclick=()=>window.desktop.startUpdate();dialog.querySelector('#closeUpdate').onclick=()=>dialog.close();close.onclick=()=>{dismissed=true;box.hidden=true;};window.desktop.onUpdate(render);window.desktop.updateState().then(render);
})();
