// Retain the whiteboard tab and storage key; migrate the old note into one positioned block.
window.createClassWhiteboard=function({read,put}){
 const el=document.createElement('section');el.id='whiteboardScreen';el.hidden=true;el.setAttribute('role','tabpanel');el.setAttribute('aria-labelledby','whiteboardTab');
 el.innerHTML=`<div class="whiteboard-toolbar"><strong>화이트보드</strong><button id="whiteboardPen">펜</button><button id="whiteboardEraser">지우개</button><input type="color" id="whiteboardColor" value="#262b33" aria-label="펜 색상"><button id="whiteboardTyping">글자 입력</button><button id="whiteboardFontMinus" aria-label="화이트보드 글자 작게">A−</button><output id="whiteboardFontSize"></output><button id="whiteboardFontPlus" aria-label="화이트보드 글자 크게">A+</button><button id="whiteboardUndo">되돌리기</button><button id="whiteboardClear">전체 지우기</button></div><div class="whiteboard-surface"><canvas id="whiteboardCanvas" aria-label="판서 화면"></canvas><div id="whiteboardTextLayer" aria-label="클릭한 위치에서 글쓰기"></div></div>`;
 document.body.append(el);const $=id=>el.querySelector('#'+id),canvas=$('whiteboardCanvas'),layer=$('whiteboardTextLayer'),ctx=canvas.getContext('2d');
 let board=read('whiteboardContents',{strokes:[],text:''});if(!board||typeof board!=='object')board={};if(!Array.isArray(board.strokes))board.strokes=[];
 const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));board.fontSize=Number.isFinite(board.fontSize)?clamp(board.fontSize,18,96):36;
 if(!Array.isArray(board.blocks))board.blocks=typeof board.text==='string'&&board.text?[{id:crypto.randomUUID(),x:.025,y:.04,width:.7,text:board.text,fontSize:board.fontSize}]:[];
 board.blocks=board.blocks.filter(b=>b&&typeof b.id==='string').map(b=>({...b,x:clamp(Number(b.x)||0,0,.95),y:clamp(Number(b.y)||0,0,.95),width:clamp(Number(b.width)||.35,.1,1),text:typeof b.text==='string'?b.text:'',fontSize:clamp(Number(b.fontSize)||36,18,96)}));
 let mode='text',selected=null,ink=null,drag=null;const nodes=new Map();
 const save=()=>put('whiteboardContents',board);
 function fontUI(){const n=board.blocks.find(b=>b.id===selected)?.fontSize||board.fontSize;$('whiteboardFontSize').textContent=n+'px';$('whiteboardFontMinus').disabled=n<=18;$('whiteboardFontPlus').disabled=n>=96;}
 function select(id){selected=id;for(const [key,node]of nodes)node.classList.toggle('selected',key===id);fontUI();}
 function layoutBlock(b){const node=nodes.get(b.id);if(!node||!layer.clientWidth||!layer.clientHeight)return;const w=layer.clientWidth,h=layer.clientHeight;const x=clamp(b.x*w,0,Math.max(0,w-100)),y=clamp(b.y*h,0,Math.max(0,h-70));node.style.left=x+'px';node.style.top=y+'px';node.style.width=clamp(b.width*w,100,w-x)+'px';const t=node.querySelector('textarea');t.style.fontSize=b.fontSize+'px';t.style.height='1px';t.style.height=Math.min(Math.max(b.fontSize*1.5,t.scrollHeight+2),h-y)+'px';}
 function renderBlock(b){const node=document.createElement('div');node.className='whiteboard-block';node.dataset.blockId=b.id;node.innerHTML='<div class="textblock-tools"><button class="textblock-move" aria-label="텍스트 이동">↔ 이동</button><button class="textblock-delete" aria-label="텍스트 삭제">삭제</button></div><textarea aria-label="화이트보드 글상자" spellcheck="false"></textarea><button class="textblock-width" aria-label="텍스트 폭 조절">↔</button>';layer.append(node);nodes.set(b.id,node);const input=node.querySelector('textarea');input.value=b.text;
  input.onpointerdown=e=>{e.stopPropagation();select(b.id);};input.onfocus=()=>select(b.id);input.oninput=()=>{b.text=input.value;layoutBlock(b);save();};
  node.querySelector('.textblock-delete').onclick=e=>{e.stopPropagation();board.blocks=board.blocks.filter(x=>x.id!==b.id);node.remove();nodes.delete(b.id);select(null);save();};
  for(const [selector,kind]of [['.textblock-move','move'],['.textblock-width','width']]){const handle=node.querySelector(selector);handle.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();e.stopPropagation();select(b.id);handle.setPointerCapture(e.pointerId);drag={id:b.id,pointer:e.pointerId,kind,startX:e.clientX,startY:e.clientY,x:b.x,y:b.y,width:b.width};};handle.onpointermove=e=>{if(!drag||drag.id!==b.id||drag.pointer!==e.pointerId)return;const w=layer.clientWidth,h=layer.clientHeight;if(kind==='move'){b.x=clamp(drag.x+(e.clientX-drag.startX)/w,0,Math.max(0,1-node.offsetWidth/w));b.y=clamp(drag.y+(e.clientY-drag.startY)/h,0,Math.max(0,1-node.offsetHeight/h));}else b.width=clamp(drag.width+(e.clientX-drag.startX)/w,100/w,1-b.x);layoutBlock(b);};handle.onpointerup=handle.onpointercancel=handle.onlostpointercapture=()=>{if(drag){drag=null;save();}};}
  node.addEventListener('pointerdown',e=>e.stopPropagation());layoutBlock(b);return input;
 }
 board.blocks.forEach(renderBlock);
 layer.onpointerdown=e=>{if(mode!=='text'||e.target!==layer||e.button!==0)return;e.preventDefault();const r=layer.getBoundingClientRect(),x=clamp((e.clientX-r.left)/r.width,0,1-110/r.width),y=clamp((e.clientY-r.top)/r.height,0,1-75/r.height);const b={id:crypto.randomUUID(),x,y,width:Math.min(.4,1-x),text:'',fontSize:board.fontSize};board.blocks.push(b);const input=renderBlock(b);select(b.id);input.focus();save();};
 function redraw(){if(el.hidden)return;const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const dpr=devicePixelRatio||1;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);for(const s of board.strokes){ctx.globalCompositeOperation=s.erase?'destination-out':'source-over';ctx.strokeStyle=s.color;ctx.lineWidth=s.erase?26:3;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();s.points.forEach((p,i)=>{if(i)ctx.lineTo(p.x*r.width,p.y*r.height);else ctx.moveTo(p.x*r.width,p.y*r.height);});if(s.points.length===1){const p=s.points[0];ctx.lineTo(p.x*r.width+.1,p.y*r.height+.1);}ctx.stroke();}ctx.globalCompositeOperation='source-over';board.blocks.forEach(layoutBlock);}
 function point(e){if(!ink)return;const r=canvas.getBoundingClientRect();ink.points.push({x:clamp((e.clientX-r.x)/r.width,0,1),y:clamp((e.clientY-r.y)/r.height,0,1)});redraw();}
 canvas.onpointerdown=e=>{if(mode==='text'||e.button!==0)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);ink={erase:mode==='erase',color:$('whiteboardColor').value,points:[]};board.strokes.push(ink);point(e);};canvas.onpointermove=point;const finish=()=>{if(ink||drag){ink=null;drag=null;save();}};canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=finish;
 function tool(next){finish();mode=next;layer.classList.toggle('ink-mode',mode!=='text');canvas.style.pointerEvents=mode==='text'?'none':'auto';for(const [id,m]of [['whiteboardPen','pen'],['whiteboardEraser','erase'],['whiteboardTyping','text']])$(id).setAttribute('aria-pressed',String(m===mode));$('whiteboardUndo').disabled=mode==='text';if(mode!=='text')select(null);}
 $('whiteboardPen').onclick=()=>tool('pen');$('whiteboardEraser').onclick=()=>tool('erase');$('whiteboardTyping').onclick=()=>tool('text');
 function changeFont(delta){const b=board.blocks.find(b=>b.id===selected);const size=clamp((b?.fontSize||board.fontSize)+delta,18,96);board.fontSize=size;if(b){b.fontSize=size;layoutBlock(b);}fontUI();save();}
 $('whiteboardFontMinus').onclick=()=>changeFont(-4);$('whiteboardFontPlus').onclick=()=>changeFont(4);
 $('whiteboardUndo').onclick=()=>{board.strokes.pop();save();redraw();};
 $('whiteboardClear').onclick=()=>{if(!confirm('화이트보드의 모든 글상자와 판서를 지울까요?'))return;board.blocks=[];board.strokes=[];board.text='';layer.replaceChildren();nodes.clear();select(null);save();redraw();};
 window.addEventListener('pagehide',save);new ResizeObserver(redraw).observe(el.querySelector('.whiteboard-surface'));tool('text');fontUI();save();
 function editText(change){
  if(!change||typeof change.id!=='string'||typeof change.text!=='string')return;
  let b=board.blocks.find(b=>b.id===change.id);
  if(!b){if(!Number.isFinite(change.x)||!Number.isFinite(change.y))return;b={id:change.id,x:clamp(change.x,0,.95),y:clamp(change.y,0,.95),width:Math.min(.4,1-clamp(change.x,0,.95)),text:'',fontSize:board.fontSize};board.blocks.push(b);renderBlock(b);}
  b.text=change.text;const input=nodes.get(b.id).querySelector('textarea');if(input.value!==b.text)input.value=b.text;layoutBlock(b);save();
 }
 return {element:el,editText,snapshot:()=>board,activate(active){finish();el.hidden=!active;if(active){tool('text');requestAnimationFrame(redraw);}save();}};
};
